package fr.reeman.tools.riftbound;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Map;

import org.junit.jupiter.api.Test;

public class DeckCodeTest {

	@Test
	public void decode() {
		decode("CEAAAAAAAAAQCAAB2YAQAAIBAAAVSAABA4AAAYDK2EA5GAOVAHMADXQBAEDQAACTKVPWS5HJAHXQCAQIAAAABXIB4AA6UAPVAGRAFJICUYBACAAB6YAQ", 0);
		decode("CEAAAAAAAAAQCAAB2YAQAAIBAAAVSAABA4AAAYDK2EA5GAOVAHMADXQBAEDQAACTKVPWS5HJAHXQCAQIAAAABXIB4AA6UAPVAGRAFJICUYBACAAB6YAQ|CEAAAAAAAAAAAAAAAEAQAAPOAEAQCAAA4AAQCAYAABU52APHAE", 8);
		decode("CIAAAAAAAAAQCAAAA4AACAIAABMQAAILAAAAICIMDMOVOX3AM5UHIAIDAAACO6XYAEAQKAAABX3QDGACUABKIAQAAEBQAAAWDBOQCAQAABMHE", 8);
		decode("CIAAAAAAAAAQCAABFIAACAIAAHLACAACAQAAAKZN2UA5QAIIAMACCIRTHCNQDIIBVQA3EAIBAEAAB2IBAIBAAAEZAKUQEBADAAWTFRIB3QAQAAAA", 0);
		// Annie
		decode("CIAAAAAAAAAAEAIAACTACAIAAEDQAAACAMAAAAYJXAAQEAYAPJ6AGAYAAAFKQAN2AEAQCAABAIBQBBYB5IAQICIAAALRXKQBVMA4CAOKAHGQDEYCSQBAIAABDPAQDSQBZUAQCAIACEBQGAAJ2EA54AIAAAAA", 0);
		decode("CIAAAAAAAAAQCAAB2YAQAAIBAAAVSAABA4AAAYDK2EA5GAOVAHMADXQBAEDQAACTKVPWS5HJAHXQCAIJAAAN2APAAHVAD5IB6YAYSAVCAKSQFJQCAAAAA", 0);
	}
	
	private void decode(String code, int sideSize) {
		RawDeck deck = DeckCode.decode(code);
		deck = deck.noVariantCopy();
		assertEquals(56, sizeOf(deck.getMain()));
		assertEquals(sideSize, sizeOf(deck.getSide()));
	}

	private int sizeOf(Map<RawCardId, Integer> map) {
		return map.values().stream().reduce(0, Integer::sum).intValue();
	}
	
	@Test
	public void encode() {
		encode("CIAAAAAAAAAQCAAAA4AACAIAABMQAAILAAAAICIMDMOVOX3AM5UHIAIDAAACO6XYAEAQKAAABX3QDGACUABKIAQAAEBQAAAWDBOQCAQAABMHE");
		encode("CIAAAAAAAAAQCAABFIAACAIAAHLACAACAQAAAKZN2UA5QAIIAMACCIRTHCNQDIIBVQA3EAIBAEAAB2IBAIBAAAEZAKUQEBADAAWTFRIB3QAQAAAA");
		// Annie
		encode("CIAAAAAAAAAAEAIAACTACAIAAEDQAAACAMAAAAYJXAAQEAYAPJ6AGAYAAAFKQAN2AEAQCAABAIBQBBYB5IAQICIAAALRXKQBVMA4CAOKAHGQDEYCSQBAIAABDPAQDSQBZUAQCAIACEBQGAAJ2EA54AIAAAAA");
	}
	
	private void encode(String code) {
		String actualCode = DeckCode.encode(DeckCode.decode(code));
		DeckCode.decode(actualCode);
		assertEquals(code, actualCode);
	}
}
